  services:
    postgres:
      image: postgres:13
      container_name: app_postgres
      restart: always
      environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
      volumes:
        - postgres_data:/var/lib/postgresql/data
        - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      ports:
        - "5433:5432"
      networks:
        - app_network

    backend:
      build: ./backend
      container_name: app_backend

      environment:
        DB_HOST: postgres
        DB_PORT: 5432
        DB_DATABASE: ${DB_NAME}
        DB_USERNAME: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        APP_ENV: local
        APP_KEY: ${APP_KEY}

      volumes:
        - ./storage/app/public:/var/www/html/storage/app/public
        - ./public/storage:/var/www/html/public/storage
        - ./backend:/var/www/html
      networks:
        - app_network

    nginx:
      image: nginx:latest
      container_name: app_nginx
      ports:
        - "8887:80"
      volumes:
        - ./backend:/var/www/html
        - ./backend/nginx.conf:/etc/nginx/conf.d/default.conf
      networks:
        - app_network

    adminer:
      image: adminer:latest
      container_name: app_adminer
      ports:
        - "8080:8080"
      restart: always
      environment:
        ADMINER_DEFAULT_SERVER: postgres
      networks:
        - app_network

  networks:
    app_network:
      driver: bridge

  volumes:
    postgres_data: