FROM php:8.3-fpm

  RUN apt-get update && apt-get install -y \
      git \
      curl \
      libpq-dev \
      libpng-dev \
      libonig-dev \
      libxml2-dev \
      zip \
      unzip \
      && docker-php-ext-install pdo pdo_pgsql mbstring exif pcntl bcmath gd

  COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

  WORKDIR /var/www/html

  COPY . .

  RUN composer install --optimize-autoloader --no-dev

  RUN chown -R www-data:www-data /var/www/html \
      && chmod -R 755 /var/www/html/storage /var/www/html/bootstrap/cache

  EXPOSE 9000

  CMD ["php-fpm"]
